<?php echo $this->helper('doctype')?>
<html>
<head>
    <title>File upload</title>
    <?php echo $this->helper('style-scripts')?>
    <?php echo $this->helper('js-scripts')?>
</head>
<body>
    <div class="wrapper">
        <div class="row">
            <div class="third centered">
                <ul class="navigation">
                    <li><a href="/">Home</a></li>
                    <li><a href="/?page=data">Add information</a></li>
                </ul>
            </div>
        </div>
        <?php echo $content ?>
    </div>
</body>
</html>
